project1/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import HomePage


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", HomePage.as_view(), name="index"),
    path("users/", include("users.urls"))
]

users/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LoginView, LogoutView

app_name = "users"

urlpatterns = [path("", HomePage.as_view(), name="index"),
                path("register/", Register.as_view(), name="register"),
               path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
               path("logout/", LogoutView.as_view(), name="logout"),
               path("list/", UserList.as_view(), name="user_list"),
               path("detail/<int:pk>/", UserDetail.as_view(), name="user_detail"),
               path("update/<int:pk>/", UpdateProfile.as_view(), name="update_profile"),
               path("delete/<int:pk>/", DeleteUser.as_view(), name="delete_user"),]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.urls import reverse

class CustomManager(BaseUserManager):
    def create_user(self, username, email, password, age, address, **extra_fields):
        if not email:
            raise ValueError(_("This is mandatory field"))

        email = self.normalize_email(email)
        user = self.model(username=username, email=email, age=age, address=address, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, username, email, password, age, address, **extra_fields):

        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_active", True)
        extra_fields.setdefault("is_superuser", True)

        if not extra_fields.get("is_superuser"):
            raise ValueError(_("Super user must have is_superuser=True"))
        if not extra_fields.get("is_staff"):
            raise ValueError(_("Super user must have is_staff=True"))
        return self.create_user(username, email, password, age, address, **extra_fields)

class CustomUser(AbstractUser):
    fullname = models.CharField(_("Full Name"), max_length=200, blank=True, default="")
    email = models.EmailField(default="")
    age = models.PositiveIntegerField(default=0)
    address = models.CharField(max_length=300, default="")

    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)

    REQUIRED_FIELDS = ['fullname', 'email', 'age', 'address']
    objects = CustomManager()

    def get_absolute_url(self):
        return reverse("users:user_detail", kwargs={'pk':self.id})

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser


class Registration(UserCreationForm):

    class Meta(UserCreationForm):
        model=CustomUser
        fields = ('username', 'email', 'fullname', 'age', 'address')

users/views.py
from django.views.generic import TemplateView, CreateView, UpdateView, DeleteView, ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .models import CustomUser
from .forms import Registration


class HomePage(TemplateView):
    template_name = "users/index.html"


class Register(CreateView):
    form_class = Registration
    success_url = reverse_lazy("index")
    template_name = "users/register.html"
    

class UserList(LoginRequiredMixin, ListView):
    model = CustomUser
    template_name = "users/user_list.html"


class UserDetail(LoginRequiredMixin, DetailView):
    model = CustomUser
    template_name = "users/user_detail.html"


class UpdateProfile(UpdateView):
    model = CustomUser
    fields = ["username", "fullname", "email", "age", "address"]
    success_url = reverse_lazy("index")
    template_name = "users/update.html"


class DeleteUser(DeleteView):
    model = CustomUser
    success_url = reverse_lazy("index")
    template_name = "users/delete_user.html"


users/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MyWebApp</title>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
<header>
    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'index' %}">WebSiteName</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{% url 'index' %}">Home</a></li>
      {% if not user.is_authenticated %}
          <li><a href="{% url 'users:register' %}">Register</a></li>
          <li><a href="{% url 'users:login' %}">Login</a></li>
      {% else %}
        <li><a href="{% url 'users:user_list' %}">UsersList</a></li>
        <li><a href="{% url 'users:update_profile' pk=user.id %}">Update Profile</a></li>
        <li><a href="{% url 'users:logout' %}">Logout</a></li>
      {% endif %}
    </ul>
  </div>
</nav>
</header>
{% block content %}
{% endblock %}
</body>
</html>

users/templates/users/delete_user.html
{% extends "users/base.html" %}
{% block content %}
    <div class="jumbotron" align="center">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Confirm Delete">
        </form>
    </div>
{% endblock %}

users/templates/users/index.html
{% extends "users/base.html" %}
{% block content %}
    <div class="jumbotron">
        {% if user.is_authenticated %}
            <h1 align="center">Welcome {{ user }}</h1>
        {% else %}
            <h2 align="center">Please Register/Login</h2>
        {% endif %}
    </div>
{% endblock %}

users/templates/users/login.html
{% extends "users/base.html" %}
{% block content %}
    <div class="jumbotron" align="center">
        <form method="POST">
            {% csrf_token %}
            <table>
                {{ form }}
            </table>
            <input type="submit" value="Login">
        </form>
        <h5>Haven't Registered Yet?<a href="{% url 'users:register' %}">Register</a></h5>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends "users/base.html" %}
{% block content %}
<div class="jumbotron" align="center">
    <form method="POST">
        {% csrf_token %}
        <table>
            {{ form }}
        </table>
        <input type="submit" value="Register">
        <h5>Already Registered?<a href="{% url 'users:login' %}">Login</a></h5>
    </form>
</div>
{% endblock %}

users/templates/users/update.html
{% extends "users/base.html" %}
{% block content %}
<div class="jumbotron" align="center">
    <form method="POST">
        {% csrf_token %}
        <table>
            {{ form }}
        </table>
        <input type="submit" value="Update">
    </form>
</div>
{% endblock %}

users/templates/users/user_detail.html
{% extends "users/base.html" %}
{% block content %}
    <div class="jumbotron">
        <h4 align="center">{{ object.username }}</h4>
        <h4 align="center">{{ object.email }}</h4>
        <h4 align="center">{{ object.fullname }}</h4>
        <h4 align="center">{{ object.age }}</h4>
        <h4 align="center">{{ object.address }}</h4>
    </div>
{% endblock %}

users/templates/users/user_list.html
{% extends "users/base.html" %}
{% block content %}
    <div>
        <ul>
            {% for usr in object_list %}
                <li><a href="{{ usr.get_absolute_url }}">{{ usr.fullname }}</a>&nbsp;&nbsp;&nbsp;<a href="{% url 'users:delete_user' pk=usr.id %}">Delete</a> </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}